#!/bin/bash
set -e

# Check if we are in the right place
if [ ! -d ./services ]; then
    echo "You must run this command from the project's root folder."
    exit 1
fi

# Set service
SERVICE=$1


# Set build command
if [[ "x$CACHE" == "xfalse" ]] ; then
    BUILD_COMMAND="docker build --no-cache"
else
    BUILD_COMMAND="docker build"
fi


# Handle build
if [[ "x$SERVICE" == "x" ]] ; then

    # Build all services
    NOCACHE=$NOCACHE webappskeleton/build postgres
    NOCACHE=$NOCACHE webappskeleton/build proxy
    NOCACHE=$NOCACHE webappskeleton/build webapp

else

    # Build a specific image
    echo ""
    if [[ "x$CACHE" == "xfalse" ]] ; then
        echo "-> Building $SERVICE (without cache)..."
    else
        echo "-> Building $SERVICE..."
    fi
    echo ""
    $BUILD_COMMAND services/$SERVICE -t webappskeleton/$SERVICE

fi
