#!/bin/bash

# Check if we are in the right place
if [ ! -d ./services ]; then
    echo "You must run this command from the project's root folder."
    exit 1
fi

webappskeleton/shell webapp "cd /code && source /env.sh && BACKEND_LOG_LEVEL=ERROR python3 manage.py core_populate"
